# Generated by Django 4.0.2 on 2022-02-17 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='user_create',
            new_name='creator',
        ),
    ]
